### ISSUE TITLE
[nit] Property attribute is inconsistent (plural vs singular)

### ISSUE THREAD

**Issue by jumattos** [Microsoft/lsif-typescript#26]
As a disclaimer, I know this issue is very nit-picky, but I thought it could be valuable to bring it up anyway.

The `property` attribute is inconsistent between different types of vertices. For example, the property for an edge between two reference results is **referenceResults**, plural. But the property for an edge from a reference result to a definition is simply **definition**, singular. As per [LSIF specification](https://github.com/Microsoft/language-server-protocol/blob/master/indexFormat/specification.md#request-textdocumentreferences), `ReferenceResult` looks like this:

```
export interface ReferenceResult {
  label: 'referenceResult';

  declarations?: (RangeId | lsp.Location)[];

  definitions?: (RangeId | lsp.Location)[];

  references?: (RangeId | lsp.Location)[];

  referenceResults?: ReferenceResultId[];
}
```

Therefore I would expect the property to be **definitions**, plural.

This kind of inconsistency happens even within LSIF. For example, the `ImplementationResult`:

```
interface ImplementationResult {
  label: 'implementationResult';

  result?: (RangeId | lsp.Location)[];

  implementationResults?: ImplementationResultId[];
}
```

Both `result` and `implementationResults` are array properties that might contain more than one item, but the former is singular and the latter, plural.

It would be less confusing if we kept everything consistent, specially as more languages adopt LSIF. It seems kind of arbitrary whether we use plural or singular for properties.

**Comment by dbaeumer** [comment]
You are correct. The property attribute should match the property name. Otherwise it gets too confusing. I will change this.

**Comment by dbaeumer** [comment]
I fixed this by making is constant a plural.
