### ISSUE TITLE
Should we support lazy results for declarations and definitions?

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/lsif-typescript#3]
this might be useful for languages like C/C++ where declarations and definitions can be spread over many files.

**Comment by LukaszMendakiewicz** [comment]
Allowing an "item" edge (with empty property) between DeclarationResult/DefinitionResult and Range for that would be great.

**Comment by dbaeumer** [comment]
I will add that to the spec then.

**Comment by dbaeumer** [comment]
Fixed for new version.

**Comment by LukaszMendakiewicz** [comment]
I didn't see this very clear in the latest specification, so I submitted https://github.com/Microsoft/language-server-protocol/pull/728 with suggested clarifications.

**Comment by dbaeumer** [comment]
@LukaszMendakiewicz thanks. Will look at the PR.
